# Configuración de SonarCloud para IUCE Reservas
# https://sonarcloud.io/project/overview?id=ShockyDEV_IUCE-Reservas-TFG

sonar.organization=shockydev
sonar.projectKey=ShockyDEV_IUCE-Reservas-TFG
sonar.projectName=IUCE Reservas TFG

# Rutas analizadas / excluidas
sonar.sources=src,prisma
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/*.d.ts
sonar.tests=src/lib/__tests__
sonar.test.inclusions=**/__tests__/**/*.test.ts

# Codificación
sonar.sourceEncoding=UTF-8
